version: '3.2'

services:
  db:
    image: mongo:4.2.24-rc0-bionic
    ports:
      - "28020:27017"
    volumes:
      - db-vloume:/data/db

  server:
    build:
      context: src/Cynthia.Card
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://host.docker.internal:28020/gwent-diy
    depends_on:
      - db

volumes:
  db-vloume: