namespace Cynthia.Card
{
    //标签
    public enum Categorie
    {
        DoubleAgent,    //双面间谍
        WildHunt,       //狂猎
        Tactic,         //谋略
        Beast,          //野兽
        Leader,         //领袖牌
        Mage,           //法师
        Boss,           //首领
        Vampire,        //吸血鬼
        Cintra,         //辛特拉
        Insectoid,      //类虫生物
        Stray,          //流亡军
        Construct,      //构造体
        Spell,          //法术
        Redania,        //瑞达尼亚
        SiegeSupport,   //攻城支援
        ClanDrummond,   //德拉蒙家族
        Specter,        //鬼灵
        Cursed,         //诅咒生物
        Soldier,        //士兵
        Kaedwen,        //科德温
        Vodyanoi,       //水生
        ClanTuirseach,  //图尔赛克家族
        ClanTordarroch, //托达洛克家族
        ClanDimun,      //迪门家族
        Witcher,        //猎魔人
        Cultist,        //呓语
        Alchemy,        //炼金
        Reckless,       //鲁莽
        ClanHeymaey,    //海玫家族
        Blitz,          //闪击
        Dryad,          //树精
        Special,        //特殊
        Elf,            //精灵
        Lyria,          //莱里亚
        Necrophage,     //食腐生物
        Machine,        //机械
        Aedirn,         //亚甸
        Support,        //辅助
        ClanAnCraite,   //奎特家族
        Dwarf,          //矮人
        Draconid,       //龙兽
        SiegeEngine,    //攻城器械
        Temeria,        //泰莫利亚
        Officer,        //军官
        Weather,        //天气
        Organic,        //有机
        Item,           //道具
        Hazard,         //灾厄
        Boon,           //恩泽
        Ambush,         //伏击
        Doomed,         //佚亡
        Bear,           //巨熊
        Ogroid,         //食人魔
        BlueStripes,    //蓝衣铁卫
        Breedable,      //繁育
        Devourer,       //吞食者
        Dragon,         //巨龙
        Harpy,          //鹰身女妖
        Medic,          //医生
        Stubborn,       //坚守
        Permadeath,     //永逝
        Peasant,        //农民
        Potion,         //药水
        Relict,         //残物
        Regressing,     //回溯
        Shapeshifter,   //变身
        Token,          //退场
        Agent,          //密探
        ClanBrokvar,    //布洛克瓦尔家族
        Human,          //人类 
        Bomb,           //炸弹
        Druid,          //德鲁伊
        Nature,         //自然
        Warfare,        //战争
        Bandit,         //匪徒
        Demon,          //恶魔
        Mutant,         //突变
        Aristocrat,     //望族
        Plant,          //植物
        Halfling,       //半身人
        Knight,         //骑士
        Location,       //地点
        Scenario,       //剧情
        Cleric,         //传教士
        Pirate,         //水手
        Firesworn,      //火誓者
        Trap,           //陷阱
        Gnome,          //侏儒
        Treant,         //树人
        Naiad,          //水精
        Raid,           //征战
        Crime,          //罪行
        Test,           //测试
    }
}
