name: .NET Core

on:
  push:
    branches-ignore: [diy-ai]
  pull_request:
    branches-ignore: [diy-ai]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 dotnet build --configuration Release ./src/Cynthia.Card/src/Cynthia.Card.Server/Cynthia.Card.Server.csproj
